- name: Cleaning temporary area before start
  file:
    path: '{{item}}'
    state: absent
  with_items:
    - '{{role_path}}/tmp/'

- name: Creating directories
  file:
    path: '{{item}}'
    state: directory
  with_items:
    - '{{role_path}}/tmp/remote'
    - '{{role_path}}/tmp/local'
    - '{{role_path}}/tmp/remote/etc/zookeeper'
    - '{{role_path}}/tmp/remote/var/lib/zookeeper'

- name: Creating zoo.cfg file
  blockinfile:
    path: "{{role_path}}/tmp/remote/etc/zookeeper/zoo.cfg"
    create: yes
    marker: ";"
    content: |
      tickTime=2000
      dataDir=/var/lib/zookeeper
      clientPort=2181
      initLimit=5
      syncLimit=2

- name: Downloading zookeeper
  get_url:
    url: '{{zookeeper.download_url}}'
    dest: '{{role_path}}/tmp/remote/zookeeper-{{zookeeper.version}}.tar.gz'

- name: Preparing Dockerfile
  template:
    src: Dockerfile.j2
    dest: '{{role_path}}/tmp/local/Dockerfile'

- name: Preparing zookeeper_start.sh
  template:
    src: zookeeper_start.sh.j2
    dest: '{{role_path}}/tmp/remote/zookeeper_start.sh'
    mode: "555"

- name: Preparing zookeeper_config.py
  template:
    src: zookeeper_config.py.j2
    dest: '{{role_path}}/tmp/remote/zookeeper_config.py'
    mode: "555"


- name: Creating tarball of files to copy inside container
  archive:
    path: '{{role_path}}/tmp/remote/'
    dest: '{{role_path}}/tmp/local/file.tar'


- name: Creating zookeeper image
  docker_image:
    name: '{{zookeeper.docker.image.name}}'
    tag: latest
    state: present
    build:
      path: '{{role_path}}/tmp/local'
    source: build

- name: Preparing kubernetes deployments.yml file
  template:
    src: deployments.yml.j2
    dest: '{{role_path}}/tmp/local/deployments.yml'