---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-1-deploy
  labels:
    app: zk-1-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk-1-pod
  template:
    metadata:
      labels:
        app: zk-1-pod
    spec:
      containers:
      - name: zookeeper
        image: zookeeper-3.5.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-2-deploy
  labels:
    app: zk-2-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk-2-pod
  template:
    metadata:
      labels:
        app: zk-2-pod
    spec:
      containers:
      - name: zookeeper
        image: zookeeper-3.5.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-3-deploy
  labels:
    app: zk-3-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk-3-pod
  template:
    metadata:
      labels:
        app: zk-3-pod
    spec:
      containers:
      - name: zookeeper
        image: zookeeper-3.5.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
---
